package com.deni.assetpnssite.models

data class DataModel(
    val kodeAsset: String? = null,
    val coaAsset: String? = null,
    val kategoriAsset: String? = null,
    val subCoaAsset: String? = null,
    val subKategoriAssets: String? = null,
    val namaAsset: String? = null,
    val merkDanSpesifikasi: String? = null,
    val kodeSistem: String? = null,
    val jumlah: String? = null,
    val tanggalPerolehan: String? = null,
    val hargaPerolehan: String? = null,
    val nomorSeri: String? = null,
    val nomorMesin: String? = null,
    val departemen: String? = null,
    val section: String? = null,
    val estate: String? = null,
    val lokasi: String? = null,
    val user: String? = null,
    val kondisi: String? = null,
    val spb: String? = null,
    val tanggalBkb: String? = null,
    val bkb: String? = null,
    val alokasi: String? = null,
    val keterangan: String? = null,
    val umur: String? = null,
    val tanggalAkhirSusut: String? = null,
    val nomorDisposal: String? = null,
    val status: String? = null,
)